### ISSUE TITLE
Writable and writable

### ISSUE THREAD

**Issue by furozen** [pyoner/svelte-types#4]
HI!
I've faced with error "semantic error TS2724: Module '"svelte/store"' has no exported member 'Writable'. Did you mean 'writable'?"

`
import {Writable, writable} from 'svelte/store';

export const direction:Writable<string> = writable('');
export const angle = writable(0);
export const isFiring = writable(false);
export const lastFireAt = writable(0);

export interface IBulllet {
  id:number|(()=>number);
  x:number;
  y:number;
  angle:number;
}

export const bulletList:Writable<IBulllet[]>  = writable([]);
`
I had had to extract Writable to separate file to fix it.
the file is there https://github.com/furozen/svelte-war/blob/master/src/stores/cannon.ts

to reproduce the error just change 1st import line as above code and remove second import line.

Maybe it's something with the project setting

**Comment by pyoner** [comment]
Hi, use `WritableStore` instead `Writable` https://github.com/pyoner/svelte-types/blob/master/types/svelte/store.d.ts#L6

**Comment by furozen** [comment]
Hi, it seems the trouble is on other flat.
there is copy of types : node_modules/svelte/types/store.d.ts and node_modules/@pyoner/svelte-types/types/svelte/store.d.ts
and in it use first path for typing. And it seems one that copied to node_modules/svelte has version 3.1.0.

**Comment by pyoner** [comment]
`Svelte` made a migration to `typescript` and now it support types definitions out the box https://github.com/sveltejs/svelte/commit/c29c389a72fe4fe130d58728c1c95e826ac1ba1d

You can remove `@pyoner/svelte-types` dependency
