### ISSUE TITLE
Why derived store can't accept WritableStore?

### ISSUE THREAD

**Issue by aimuzov** [pyoner/svelte-types#6]
https://github.com/pyoner/svelte-types/blob/f85b49c245f639982a1aa662711d273657ec6db1/types/svelte/store.d.ts#L22

@pyoner, why I got TS error if `WritableStore` extends `ReadableStore`?

## Example:
```ts
interface SomeInfo {
    [key: string]: string;
}

const store1: WritableStore<SomeInfo | null> = writable(null);

const store2: ReadableStore<{}> = derived<SomeInfo>(
    // Argument of type 'WritableStore<SomeInfo | null>' is not assignable to parameter of type 'ReadableStore<SomeInfo>[]'.
    // Type 'WritableStore<SomeInfo | null>' is missing the following properties from type 'ReadableStore<SomeInfo>[]': length, pop, push, concat, and 26 more.
    store1,
    ($store1: SomeInfo): {} => {
        return {
            $store1,
            additionalKey: "for example",
        };
    },
);
```

**Comment by pyoner** [comment]
Hi @immuzov 
Svelte now supports types (from ver. 3.4.4)

You can try new template https://github.com/pyoner/svelte-typescript/tree/master/packages/template
The project moved to this monorepo https://github.com/pyoner/svelte-typescript

**Comment by aimuzov** [comment]
Thank you for your answer!
